CC = g++

all:
	$(CC) partition_seq.cpp -o partition_seq
	$(CC) partition_single.cpp -o partition_single
	$(CC) partition_two.cpp -o partition_two

clean:
	rm -f partition_seq partition_single partition_two